---
- name: install and start apache and configure firewall
  hosts: all
  become: yes
  tasks:
   - name: latest version of firewalld and httpd package is present
     yum:
        name:
           - httpd
           - firewalld
        state: latest
   - name: test html page is installed
     copy:
        content: "Welcome to the example.com intranet!\n"
        dest: /var/www/html/index.html
   - name: firewalld enabled and running
     service:
        name: firewalld
        enabled: true
        state: started
   - name: firewalld permits http service
     firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
   - name: httpd enabled and running
     service:
        name: httpd
        enabled: true
        state: started
- name: Test intranet web server
  hosts: localhost
  become: no 
  tasks:
   - name: connect to intranet web server
     uri:
        url: http://127.0.0.1/index.html
        return_content: yes
        status_code: 200
