---
- name: install httpd service
  hosts: all
  become: yes
  tasks:
   - name: install httpd package
     yum:
        name: httpd
        state: latest
     register: httpd_result
   - name: restart httpd
     service:
        name: httpd
        state: restart
     when: httpd_result.changed

